@echo off
echo unzipping prepared-eclipse in silent mode (please wait) ...
unzip -q archs2unzip\prepared-eclipse.zip -d "%USERPROFILE%\progs"
echo unzipping Maven 3 in silent mode (please wait) ...
unzip -q archs2unzip\apache-maven-3.0.2-bin.zip -d "%USERPROFILE%\progs"
pause